#!/system/bin/sh
#
# The mother-load of all scripts O.O
#
# This script is designed to act similarly to busybox in how it
# can have symlinks of it made and whatnot to run the commands.
#

SCRIPT_NAME=scriptybox
SYSTEM_ETC=/system/etc
SCRIPT_ETC="${SYSTEM_ETC}/scriptybox"

# first assume we're using a symbolic link
CMD=$(basename $0)
ARG=$@

# ensure we are getting an argument
if busybox [ ! -z "${ARG}" ] ; then
	# if we are calling the script directly, shift the args
	if busybox [ "$(busybox basename $0)" == "${SCRIPT_NAME}" ] ; then
		# oh noes! direct scripting! time to shift and reset
		CMD=$1;	shift 1
		ARG=$@
	fi
fi

# now we have a command and its arguments, create some useful locations
CMD_ETC="${SCRIPT_ETC}/${CMD}"

case ${CMD} in
	camsounds) # done
		busybox mount -o remount,rw /system

		sound_clk="/system/media/audio/ui/camera_click.ogg"
		sound_rec="/system/media/audio/ui/VideoRecord.ogg"

		case ${ARG} in
			on)
				busybox echo -n "Enabling camera audio ... "
				if busybox [ -e "${sound_clk}.bak" ] ; then busybox mv "${sound_clk}.bak" "${sound_clk}"; fi
				if busybox [ -e "${sound_rec}.bak" ] ; then busybox mv "${sound_rec}.bak" "${sound_rec}"; fi
				busybox echo "done"
				;;
			off)
				busybox echo -n "Disabling camera audio ... "
				if busybox [ -e "${sound_clk}" ] ; then busybox mv "${sound_clk}" "${sound_clk}.bak"; fi
				if busybox [ -e "${sound_rec}" ] ; then busybox mv "${sound_rec}" "${sound_rec}.bak"; fi
				busybox echo "done"
				;;
			*)
				busybox echo "Usage:"
				busybox echo "    camsounds [on|off]"
				busybox echo ""
				busybox echo "Turns the camera sounds (shutter and video cam) on or off"
				;;				
		esac

		busybox mount -o remount,ro /system
		sync
		;;
	cpuinfo) # done
		if busybox [ -z "${ARG}" ] ; then
			busybox cat /proc/cpuinfo
		else
			busybox echo "Usage:"
			busybox echo "    cpuinfo"
			busybox echo ""
			busybox echo "Displays all of the CPU information for the system"
		fi
		;;
	dalvikjit) # done
		busybox mount -o remount,rw /system

		case ${ARG} in
			on)
				busybox echo -n "Enabling JIT compiler in Dalvik ... "
				busybox sed -r -i 's/(dalvik\.vm\.execution-mode=int:)fast/\1jit/' /system/build.prop
				busybox echo "done"
				;;
			off)
				busybox echo -n "Disabling JIT compiler in Dalvik ... "
				busybox sed -r -i 's/(dalvik\.vm\.execution-mode=int:)jit/\1fast/' /system/build.prop
				busybox echo "done"
				;;
			*)
				busybox echo "Usage:"
				busybox echo "    dalvikjit [on|off]"
				busybox echo ""
				busybox echo "Enables/disables the JIT compiler for the dalvik"
				busybox echo "virtual machine."
				;;
		esac

		busybox echo ""
		busybox echo "NOTE: REQUIRES A REBOOT TO ACTIVATE"
		busybox echo ""
		busybox echo "WARNING: THIS IS THE ECLAIR JIT COMPILER AND THEREFORE"
		busybox echo "         IS STILL SOMEWHAT UNSTABLE!  USE AT YOUR OWN"
		busybox echo "         RISK!"

		busybox mount -o remount,ro /system
		sync
		;;
	freemem) # done
		case ${ARG} in
			50mb)
				# 10mb,15mb,25mb,30mb,40mb,50mb
				busybox echo -n "Setting memkiller to keep 50mb of RAM free ... "
				busybox echo "2560,3840,6400,7680,10240,12800" > /sys/module/lowmemorykiller/parameters/minfree
				busybox echo "done"
				;;
			75mb)
				# 10mb,15mb,25mb,40mb,50mb,75mb
				busybox echo -n "Setting memkiller to keep 75mb of RAM free ... "
				busybox echo "2560,3840,6400,10240,12800,19200" > /sys/module/lowmemorykiller/parameters/minfree
				busybox echo "done"
				;;
			100mb)
				# 10mb,15mb,25mb,50mb,70mb,100mb
				busybox echo -n "Setting memkiller to keep 100mb of RAM free ... "
				busybox echo "2560,3840,6400,12800,12800,25600" > /sys/module/lowmemorykiller/parameters/minfree
				busybox echo "done"
				;;
			default)
				# 6mb,8mb,16mb,20mb,22mb,24mb (default)
				busybox echo -n "Setting memkiller to keep 24mb of RAM free (default) ... "
				busybox echo "1536,2048,4096,5120,5632,6144" > /sys/module/lowmemorykiller/parameters/minfree
				busybox echo "done"
				;;
			*)
				busybox echo "Usage:"
				busybox echo "    freemem [50mb|75mb|100mb|default]"
				busybox echo ""
				busybox echo "Configures the system to enusre that at least a given"
				busybox echo "amount of RAM is always available"
				;;
		esac
		;;
	meminfo) # done
		if busybox [ -z "${ARG}" ] ; then
			busybox cat /proc/meminfo
		else
			busybox echo "Usage:"
			busybox echo "    meminfo"
			busybox echo ""
			busybox echo "Displays all of the memory information for the system"
		fi
		;;
	rmapk) # done
		APP_NAME=""
		APP_FILES=""

		case ${ARG} in
			alarm)
				APP_NAME="Alarm Clock"
				APP_FILES="/system/app/AlarmClock.apk"
				;;
			browser)
				APP_NAME="Browser"
				APP_FILES="/system/app/Browser.apk"
				;;
			calc)
				APP_NAME="Calculator"
				APP_FILES="/system/app/Calculator.apk"
				;;
			carhome)
				APP_NAME="Car Home"
				APP_FILES="/system/app/CarDock.apk"
				;;
			corpcal)
				APP_NAME="Corporate Calendar"
				APP_FILES="/system/app/CorpCal.apk"
				;;
			deskclock)
				APP_NAME="Desk Clock"
				APP_FILES="/system/app/DeskClock.apk"
				;;
			devtools)
				APP_NAME="Dev Tools"
				APP_FILES="/system/app/Development.apk"
				;;
			#dock)
			#	APP_NAME="Dock"
			#	APP_FILES="/system/app/Dock.apk"
			#	;;
			email)
				APP_NAME="Email"
				APP_FILES="/system/app/Email.apk"
				;;
			genie)
				APP_NAME="News and Weather"
				APP_FILES="/system/app/GenieWidget.apk"
				;;
			#im)
			#	APP_NAME="IM"
			#	APP_FILES="/system/app/IM.apk"
			#	;;
			lwps)
				APP_NAME="Live Wallpapers"
				APP_FILES="/system/app/LiveWallpapers.apk /system/app/MagicSmokeWallpapers.apk /system/app/VisualizationWallpapers.apk"
				;;
			mms)
				APP_NAME="MMS"
				APP_FILES="/system/app/Mms.apk"
				;;
			mp3)
				APP_NAME="Amazon MP3"
				APP_FILES="/system/app/com.amazon.mp3.apk"
				;;
			qoffice)
				APP_NAME="QuickOffice"
				APP_FILES="/system/app/QuickOffice.apk"
				;;
			spare)
				APP_NAME="Spare Parts"
				APP_FILES="/system/app/SpareParts.apk"
				;;
			*)
				busybox echo "Usage:"
				busybox echo "     rmapk [alarm|browser|calc|carhome|corpcal|"
				busybox echo "            deskclock|devtools|email|genie|lwps|"
				busybox echo "            mms|mp3|qoffice|spare]" # dock, im
				busybox echo ""
				busybox echo "Removes applications that may be unwanted on some"
				busybox echo "systems.  The Applications are:"
				busybox echo "     alarm - Alarm Clock"
				busybox echo "     browser - Stock browser"
				busybox echo "     calc - Stock calculator"
				busybox echo "     carhome - Stock car home"
				busybox echo "     corpcal - Corporate Calendar"
				busybox echo "     deskclock - Desk Clock"
				busybox echo "     devtools - Development Tools"
				#busybox echo "     dock - Dock"
				busybox echo "     email - Stock email"
				busybox echo "     genie - News and Weather"
				#busybox echo "     im - Stock IM"
				busybox echo "     lwps - Live Wallpapers"
				busybox echo "     mms - Stock MMS"
				busybox echo "     mp3 - Amazon MP3"
				busybox echo "     qoffice - QuickOffice"
				busybox echo "     spare - Spare Parts"
				;;
		esac

		if busybox [ ! -z "${APP_NAME}" ] ; then
			busybox echo "Removing application: ${APP_NAME}"

			busybox mount -o remount,rw /system

			for apk in ${APP_FILES}; do
				busybox echo -n "  Removing file: ${apk} ... "

				if busybox [ -e "${apk}" ] ; then
					# i am basenaming this to make sure nothing bad happens
					busybox rm "/system/app/$(busybox basename ${apk})"
					busybox echo "done"
				else
					busybox echo "already removed"
				fi
			done

			busybox mount -o remount,ro /system
			sync
		fi
		;;
	shutdown) # done
		if busybox [ -z "${ARG}" ] ; then
			busybox echo "Powering down ... "
			reboot -p
		else
			busybox echo "Usage:"
			busybox echo "    shutdown"
			busybox echo ""
			busybox echo "Powers off the phone"
		fi
		;;
	sysro) # done
		if busybox [ -z "${ARG}" ] ; then
			busybox echo -n "Remounting /system read-only"
			busybox mount -o remount,ro /system
			busybox echo "done"
			busybox echo -n "Syncing ... "
			sync
			busybox echo "done"
		else
			busybox echo "Usage:"
			busybox echo "    sysro"
			busybox echo ""
			busybox echo "Mounts the /system partition read-only"
		fi
		;;
	sysrw) # done
		if busybox [ -z "${ARG}" ] ; then
			busybox echo -n "Remounting /system read-write ... "
			busybox mount -o remount,rw /system
			busybox echo "done"
		else
			busybox echo "Usage:"
			busybox echo "    sysrw"
			busybox echo ""
			busybox echo "Mounts the /system partition read/write"
		fi
		;;
	swapinfo) # done
		if busybox [ -z "${ARG}" ] ; then
			busybox cat /proc/swaps
		else
			busybox echo "Usage:"
			busybox echo "    swapinfo"
			busybox echo ""
			busybox echo "Displays all of the swap information for a system"
		fi
		;;
	zipalign_apks) # done
		if busybox [ -z "${ARG}" ] ; then
			# find our apks
			sys_apks=$(busybox find /system -name '*.apk')
			dat_apks=$(busybox find /data -name '*.apk')

			# zipalign apks
			busybox mount -o remount,rw /system
			for apk in ${sys_apks} ${dat_apks}; do
				apk_name="$(busybox basename ${apk})"
				apk_cache="/cache/${apk_name}"

				# check if we are already zipaligned
				if ! zipalign -c 4 ${apk} ; then
					busybox echo -n "${apk} - ZipAligning ... "

					# nope, time to zipalign
					zipalign -f 4 "${apk}" "${apk_cache}"

					# check if file exists
					if busybox [ -e "${apk_cache}" ] ; then
						busybox cp -f "${apk_cache}" "${apk}"
						busybox rm "${apk_cache}"

						busybox echo "done";
					else
						busybox echo "ERROR";
					fi
				else
					busybox echo "${apk} - Already ZipAligned. Skipping"
				fi
			done
			busybox mount -o remount,ro /system
			sync
		else
			busybox echo "Usage:"
			busybox echo "    zipalign_apks"
			busybox echo ""
			busybox echo "Automagickally zipaligns all of the APK files found on your system"
			busybox echo "NOTE: THIS WILL ZIPALIGN ANY APK UNDER /system OR /data"
		fi
		;;
	*)
		busybox echo "Available commands:"
		busybox echo ""
		busybox echo "     camsounds [on|off]"
		busybox echo "     cpuinfo"
		busybox echo "     freemem [50mb|75mb|100mb|default]"
		busybox echo "     dalvikjit [on|off]"
		busybox echo "     meminfo"
		busybox echo "     rmapk [browser|calc|carhome|corpcal|"
		busybox echo "            devtools|dock|email|genie|im|"
		busybox echo "            lwps|mms|mp3|qoffice|spare]"
		busybox echo "     shutdown"
		busybox echo "     sysro"
		busybox echo "     sysrw"
		busybox echo "     swapinfo"
		busybox echo "     zipalign_apks"
		;;
esac

busybox echo ""
busybox echo "(Android $(getprop ro.build.version.release) / $(getprop ro.build.display.id) [$(getprop ro.build.id)] by $(getprop ro.rommanager.developerid))"
